# Generated by Django 5.1.1 on 2024-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=30)),
                ('fechaNacimiento', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('paisOrigen', models.CharField(max_length=30)),
            ],
        ),
    ]
